# -*- coding: utf-8 -*-
"""preprocessing_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nc2jgBvHWXefX1pHHFl8VxKKSEOU0WCc
"""

# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir("/content/drive/My Drive/SIH_2020")
!ls

from osgeo import gdal
import numpy as np
import sys
import rasterio
from matplotlib import pyplot

# Plot Band 
def plotBand( ds, num, color):
    myarray1 = np.array(ds.GetRasterBand(num).ReadAsArray())
    pyplot.imshow(myarray1, cmap= color)
    pyplot.show()   
    return


path = 'Clipped_NDVI/'
for img in os.listdir(path):
  print(img)
  ds = gdal.Open(os.path.join(path,img))
  print(ds)
  # Plot band 1
  plotBand(ds, 1, 'Accent')

